[project]
name = "renomia-hackathon"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "mypy>=1.19.1",
    "ruff>=0.15.5",
]

[tool.uv]
managed = true
package = false

[tool.uv.workspace]
members = [
    "services/*",
    "packages/*",
]

[tool.uv.sources]
renomia-ai = { workspace = true, editable = true }

